### ISSUE TITLE
Stack canary watchpoint triggered (btController) -> vTaskSwitchContext -> /freertos/tasks.c line 3435 (IDFGH-7683)

### ISSUE THREAD

**Issue by sepp89117** [sepp89117/GoPro_BLE_RC#1]
https://github.com/espressif/arduino-esp32/issues/6915

I use ESP32 Dev Module
I have esp32 Version 2.0.3 installed
I use WiFi and BLE together
Sometimes is working fine

Code snippet:
```cpp
#include <WiFi.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include "BLEDevice.h"

WebServer server(80);

struct GoProCam {
  BLEAdvertisedDevice* pDevice = nullptr;
  BLEClient* pClient = nullptr;
  bool toConnect = false;
  bool isAuth = false;
  bool isConnected = false;
  uint32_t lastKeepAlive = 0;
  char lastCommand[2] = {0, 0};
  char lastError[2] = {0, 0};
  BLERemoteCharacteristic* pCommandCharacteristic = nullptr;
  BLERemoteCharacteristic* pCommandRespCharacteristic = nullptr;
  BLERemoteCharacteristic* pSettingsCharacteristic = nullptr;
  BLERemoteCharacteristic* pSettingsRespCharacteristic = nullptr;
};

//... some more variables

bool connectToCam(uint8_t camIndex) {
// Set security
  BLEDevice::setEncryptionLevel(ESP_BLE_SEC_ENCRYPT);
  BLEDevice::setSecurityCallbacks(new MySecurity());
  BLESecurity *pSecurity = new BLESecurity();
  pSecurity->setAuthenticationMode(ESP_LE_AUTH_REQ_SC_BOND); //ESP_LE_AUTH_REQ_SC_ONLY
  pSecurity->setCapability(ESP_IO_CAP_OUT);
  pSecurity->setRespEncryptionKey(ESP_BLE_ENC_KEY_MASK | ESP_BLE_ID_KEY_MASK);

// Create client
  goProCams[camIndex].pClient = BLEDevice::createClient();
  goProCams[camIndex].pClient->setClientCallbacks(new MyClientCallback());

  goProCams[camIndex].pClient->connect(goProCams[camIndex].pDevice); 

//here fires BLESecurityCallbacks -> onAuthenticationComplete() = successful

//[BUG] Stack canary watchpoint triggered (btController)
  BLERemoteService* pRemoteService = goProCams[camIndex].pClient->getService(controlServiceUUID);

  //... nothing more executed
}

void setup() {
  Serial.begin(115200);
  
  WiFi.softAP(ssid, password);

  if (MDNS.begin(DomainName)) {
    Serial.println("MDNS responder started");
    MDNS.addService("http", "tcp", 80);
  }
  
  initServer(); //server.on()...
  
  BLEDevice::init(ssid);
  BLEScan* pBLEScan = BLEDevice::getScan();
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  pBLEScan->setActiveScan(true);
  pBLEScan->start(5);
}

void loop() {
  BLEDevice::getScan()->clearResults();

  server.handleClient();
  vTaskDelay(2);

  for (uint8_t i = 0; i < maxCams; i++) {
    if (goProCams[i].pDevice != nullptr) {
      if (goProCams[i].toConnect) {
        if (connectToCam(i)) {
          goProCams[i].isConnected = true;
          //...
        }
      }
    }
  }
}
```

Exception:
```
Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception). 
Debug exception reason: Stack canary watchpoint triggered (btController) 
Core  0 register dump:
PC      : 0x40094991  PS      : 0x00060036  A0      : 0x40092e07  A1      : 0x3ffe1bb0  
A2      : 0x3ffc4bf4  A3      : 0x3ffc4c1c  A4      : 0x3ffc4c1c  A5      : 0x00000001  
A6      : 0x00000000  A7      : 0x00000017  A8      : 0x3ffc4bfc  A9      : 0x3ffe1b90  
A10     : 0x3ffdb96c  A11     : 0x3ffdb96c  A12     : 0x00000014  A13     : 0x00000000  
A14     : 0x3ffdb964  A15     : 0x80000001  SAR     : 0x00000008  EXCCAUSE: 0x00000001  
EXCVADDR: 0x00000000  LBEG    : 0x40090588  LEND    : 0x4009059e  LCOUNT  : 0xffffffff  


Backtrace:0x4009498e:0x3ffe1bb00x40092e04:0x3ffe1be0 0x40092db4:0xa5a5a5a5  |<-CORRUPTED
```

Decoding stack results
```
0x4009498e: vTaskSwitchContext at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c line 3435
```

**Comment by sepp89117** [comment]
@KonradIT @hellolwt
With esp32 version 1.0.6 the new code works fine for me
I have updated for testing
Check out the new web server interface ;)

**Comment by KonradIT** [comment]
Shutter on/off , wifi AP on/off , hilight tag works! UI looks cool too. Tested on Hero9 and Hero10.

Mode change fails

![imagen](https://user-images.githubusercontent.com/5891284/175654354-680552f3-6327-41f8-ba46-e6aff39a34e5.png)

**Comment by KonradIT** [comment]
https://user-images.githubusercontent.com/5891284/175655359-5fdbd7f4-b391-4158-9720-575f41e4f88a.mp4

**Comment by sepp89117** [comment]
Thanks!  The commands are from open gopro and are actually for hero 9 and 10. I'll find out why they don't work.  They don't work for me on the 8 either.  I get success response but nothing happens.

**Comment by hellolwt** [comment]
Shutter on/off , wifi AP on/off , sleep tag works on two Hero10s.
![捕获](https://user-images.githubusercontent.com/78248878/175755432-aa55365a-14a1-41c1-90ee-7821d9efb895.JPG)

**Comment by hellolwt** [comment]
Mode change fails too
![捕获2](https://user-images.githubusercontent.com/78248878/175755726-62374154-4492-450d-9c8f-61596dd8a589.JPG)

**Comment by sepp89117** [comment]
New update for today. Preset loads should now work

**Comment by hellolwt** [comment]
Now I can't open the http, sometimes I can't connect to ESP WiFi. Do you know what happened ?

**Comment by sepp89117** [comment]
Some infos on serial monitor? Maybe crash now with gopro 10s? Check serial! What is serial and model output on serial ?

**Comment by hellolwt** [comment]
I reset the connect setting of Hero10 and try again, it did connect two cams but only see one cam on http. I check the serial and see two many not-GoPro device😂. Is that the problem?

![捕获1](https://user-images.githubusercontent.com/78248878/175782864-f1f83b08-a944-4d50-b53e-c04210f5ea2e.JPG)

![捕获2](https://user-images.githubusercontent.com/78248878/175782874-860a799d-5232-43b8-b004-d45968708a3b.JPG)

**Comment by sepp89117** [comment]
What is your esp32 version?
In your Arduino IDE, go to File> Preferences. 
Go to Tools > Board > Boards Manager…
Search for ESP32 and and check version installed.

With 2.0.3 i have simliar problems. With 1.0.6 runns great. Maybe your problem too?

**Comment by hellolwt** [comment]
I did install version 1.0.6. Whenever I try to connect the second cam it crash. It still runs fine before update.

**Comment by sepp89117** [comment]
I'm sorry that I only have one camera at the moment and need your help. 
Is it working now?

**Comment by hellolwt** [comment]
Still the same problem.

![捕获2](https://user-images.githubusercontent.com/78248878/175810374-e8a73b70-b3ed-464b-8891-f79d0950022f.JPG)
![捕获](https://user-images.githubusercontent.com/78248878/175810376-099bbe96-20fd-4c10-bdd2-1bf05e51eb79.JPG)

**Comment by sepp89117** [comment]
That was probably the last update. I've tried everything, but unfortunately I'm at the end! A camera needs over 20 kb. Therefore it is probably hardly possible to connect many cameras.
As long as no one has any good suggestions, I'll stop working on it for now.
sorry

**Comment by hellolwt** [comment]
It's ok. I think the first version of your code works fine, being able to control cams is good enough. Thanks for your efforts!

**Comment by sepp89117** [comment]
New web browser based project released. Interesting?
https://github.com/sepp89117/GoPro_Web_RC

**Comment by KonradIT** [comment]
You should enable github pages on that repository, so the website is accessible like: https://sepp89117.github.io/GoPro_Web_RC/GoPro_Web_RC.html

**Comment by sepp89117** [comment]
Thank you for the hint ! I did it like this

**Comment by KonradIT** [comment]
![image](https://user-images.githubusercontent.com/5891284/177041187-8028fc1a-514e-415f-b344-e505961147d7.png)

works nicely with 2 cameras))

**Comment by sepp89117** [comment]
That makes me happy! Thanks for your feedback!

**Comment by hellolwt** [comment]
Great! It works good on 2 Hero10s too.
